#ifndef STD_RTI_SYMBOLS_H
#define STD_RTI_SYMBOLS_H
#include <j3dcore/j3d.h>
#include <std/types.h>

// Extra definition
#define stdio_open_TYPE tFileHandle (J3API*)(char *Filename, char *mode)

#define stdControl_Startup_TYPE int (J3DAPI*)(int)
#define stdControl_Shutdown_TYPE void (*)(void)
#define stdControl_Open_TYPE int (*)(void)
#define stdControl_Close_TYPE void (*)(void)
#define stdControl_Reset_TYPE void (*)(void)
#define stdControl_DisableReadJoysticks_TYPE void (*)(void)
#define stdControl_EnableAxis_TYPE int (J3DAPI*)(size_t)
#define stdControl_ReadControls_TYPE void (*)(void)
#define stdControl_ReadAxis_TYPE float (J3DAPI*)(size_t)
#define stdControl_ReadAxisRaw_TYPE int (J3DAPI*)(size_t)
#define stdControl_ReadKeyAsAxis_TYPE float (J3DAPI*)(size_tt)
#define stdControl_ReadAxisAsKey_TYPE int (J3DAPI*)(size_t, int*)
#define stdControl_ReadAxisAsKeyEx_TYPE int (J3DAPI*)(size_t, int*, float)
#define stdControl_ReadKey_TYPE int (J3DAPI*)(size_t, int*)
#define stdControl_ControlsActive_TYPE int (*)(void)
#define stdControl_SetActivation_TYPE int (J3DAPI*)(int)
#define stdControl_ToggleMouse_TYPE int (*)(void)
#define stdControl_EnableMouse_TYPE int (J3DAPI*)(int)
#define stdControl_ControlsIdle_TYPE int (*)(void)
#define stdControl_TestAxisFlag_TYPE int (J3DAPI*)(size_t, StdControlAxisFlag)
#define stdControl_SetAxisFlags_TYPE void (J3DAPI*)(size_t, StdControlAxisFlag)
#define stdControl_InitJoysticks_TYPE void (J3DAPI*)()
#define stdControl_InitKeyboard_TYPE void (J3DAPI*)(int)
#define stdControl_InitMouse_TYPE void (J3DAPI*)()
#define stdControl_EnableAxisRead_TYPE void (J3DAPI*)(size_t)
#define stdControl_ReadKeyboard_TYPE void (*)(void)
#define stdControl_ReadJoysticks_TYPE void (*)(void)
#define stdControl_ReadMouse_TYPE void (J3DAPI*)()
#define stdControl_RegisterAxis_TYPE void (J3DAPI*)(size_t, int, int, float)
#define stdControl_DIGetStatus_TYPE const char* (J3DAPI*)(int)
#define stdControl_EnumDevicesCallback_TYPE BOOL (__stdcall*)(LPCDIDEVICEINSTANCEA, LPVOID)
#define stdControl_ResetMousePos_TYPE void (*)(void)
#define stdControl_GetMaxJoystickButtons_TYPE size_t (*)(void)
#define stdControl_GetNumJoysticks_TYPE size_t (*)(void)
#define stdControl_EnableMouseSensitivity_TYPE void (J3DAPI*)(int)
#define stdControl_ShowMouseCursor_TYPE void (J3DAPI*)(int)
#define stdControl_IsGamePad_TYPE int (J3DAPI*)(int)
#define stdDisplay_Startup_TYPE int (*)(void)
#define stdDisplay_Shutdown_TYPE void (*)(void)
#define stdDisplay_Open_TYPE int (J3DAPI*)(size_t)
#define stdDisplay_Close_TYPE void (*)(void)
#define stdDisplay_SetMode_TYPE int (J3DAPI*)(size_t, int, size_t)
#define stdDisplay_ClearMode_TYPE void (*)(void)
#define stdDisplay_GetNumDevices_TYPE size_t (*)(void)
#define stdDisplay_GetDevice_TYPE int (J3DAPI*)(size_t, StdDisplayDevice*)
#define stdDisplay_GetCurrentDevice_TYPE int (J3DAPI*)(StdDisplayDevice*)
#define stdDisplay_Refresh_TYPE void (J3DAPI*)(int)
#define stdDisplay_VBufferNew_TYPE tVBuffer* (J3DAPI*)(const tRasterInfo*, int, int)
#define stdDisplay_VBufferFree_TYPE void (J3DAPI*)(tVBuffer*)
#define stdDisplay_VBufferLock_TYPE int (J3DAPI*)(tVBuffer*)
#define stdDisplay_VBufferUnlock_TYPE int (J3DAPI*)(tVBuffer*)
#define stdDisplay_VBufferFill_TYPE int (J3DAPI*)(tVBuffer*, uint32_t, const StdRect*)
#define stdDisplay_VBufferConvertColorFormat_TYPE tVBuffer* (J3DAPI*)(const ColorInfo*, tVBuffer*, int, LPDDCOLORKEY)
#define stdDisplay_VideoModeCompare_TYPE int (J3DAPI*)(const StdVideoMode*, const StdVideoMode*)
#define stdDisplay_GetTextureMemory_TYPE int (J3DAPI*)(size_t*, size_t*)
#define stdDisplay_GetTotalMemory_TYPE int (J3DAPI*)(size_t*, size_t*)
#define stdDisplay_DDGetStatus_TYPE const char* (J3DAPI*)(HRESULT)
#define stdDisplay_CreateZBuffer_TYPE int (J3DAPI*)(LPDDPIXELFORMAT, int)
#define stdDisplay_InitDirectDraw_TYPE int (J3DAPI*)(HWND hwnd)
#define stdDisplay_ReleaseDirectDraw_TYPE void (J3DAPI*)()
#define stdDisplay_DDEnumCallback_TYPE BOOL (__stdcall*)(GUID*, LPSTR, LPSTR, LPVOID)
#define stdDisplay_EnumVideoModesCallback_TYPE HRESULT (__stdcall*)(LPDDSURFACEDESC2, LPVOID)
#define stdDisplay_SetAspectRatio_TYPE void (J3DAPI*)(StdVideoMode*)
#define stdDisplay_GetDirectDraw_TYPE LPDIRECTDRAW4 (*)(void)
#define stdDisplay_SetWindowMode_TYPE int (J3DAPI*)(HWND, StdVideoMode*)
#define stdDisplay_SetFullscreenMode_TYPE int (J3DAPI*)(HWND, const StdVideoMode*, size_t)
#define stdDisplay_ReleaseBuffers_TYPE void (J3DAPI*)()
#define stdDisplay_LockSurface_TYPE uint8_t* (J3DAPI*)(tVSurface*)
#define stdDisplay_UnlockSurface_TYPE int (J3DAPI*)(tVSurface*)
#define stdDisplay_Update_TYPE int (*)(void)
#define stdDisplay_ColorFillSurface_TYPE int (J3DAPI*)(tVSurface*, uint32_t, const StdRect*)
#define stdDisplay_BackBufferFill_TYPE int (J3DAPI*)(uint32_t, const StdRect*)
#define stdDisplay_SaveScreen_TYPE int (J3DAPI*)(const char*)
#define stdDisplay_SetDefaultResolution_TYPE void (J3DAPI*)(uint32_t, uint32_t)
#define stdDisplay_GetBackBufferSize_TYPE void (J3DAPI*)(uint32_t*, uint32_t*)
#define stdDisplay_GetNumVideoModes_TYPE size_t (*)(void)
#define stdDisplay_GetVideoMode_TYPE int (J3DAPI*)(size_t, StdVideoMode*)
#define stdDisplay_GetCurrentVideoMode_TYPE int (J3DAPI*)(StdVideoMode*)
#define stdDisplay_GetFrontBufferDC_TYPE HDC (*)(void)
#define stdDisplay_ReleaseFrontBufferDC_TYPE void (J3DAPI*)(HDC)
#define stdDisplay_GetBackBufferDC_TYPE HDC (*)(void)
#define stdDisplay_ReleaseBackBufferDC_TYPE void (J3DAPI*)(HDC)
#define stdDisplay_FlipToGDISurface_TYPE int (*)(void)
#define stdDisplay_CanRenderWindowed_TYPE int (J3DAPI*)()
#define stdDisplay_SetBufferClipper_TYPE int (J3DAPI*)(int)
#define stdDisplay_RemoveBufferClipper_TYPE HRESULT (J3DAPI*)(int)
#define stdDisplay_IsFullscreen_TYPE int (J3DAPI*)()
#define stdDisplay_LockBackBuffer_TYPE int (J3DAPI*)(void**, uint32_t*, uint32_t *, int32_t*)
#define stdDisplay_UnlockBackBuffer_TYPE void (*)(void)
#define stdDisplay_EncodeFromRGB565_TYPE uint32_t (J3DAPI*)(uint16_t)
#define std3D_Startup_TYPE int (*)(void)
#define std3D_Shutdown_TYPE void (*)(void)
#define std3D_GetNumDevices_TYPE size_t (*)(void)
#define std3D_GetAllDevices_TYPE const Device3D* (*)(void)
#define std3D_Open_TYPE int (J3DAPI*)(size_t)
#define std3D_Close_TYPE void (J3DAPI*)()
#define std3D_GetTextureFormat_TYPE void (J3DAPI*)(StdColorFormatType, ColorInfo*, int*, LPDDCOLORKEY*)
#define std3D_GetColorFormat_TYPE StdColorFormatType (J3DAPI*)(const ColorInfo*)
#define std3D_GetNumTextureFormats_TYPE size_t (*)(void)
#define std3D_StartScene_TYPE int (*)(void)
#define std3D_EndScene_TYPE void (*)(void)
#define std3D_DrawRenderList_TYPE void (J3DAPI*)(LPDIRECT3DTEXTURE2, Std3DRenderState, LPD3DTLVERTEX, size_t, LPWORD, size_t)
#define std3D_SetWireframeRenderState_TYPE void (*)(void)
#define std3D_DrawLineStrip_TYPE void (J3DAPI*)(LPD3DTLVERTEX, size_t)
#define std3D_DrawPointList_TYPE void (J3DAPI*)(LPD3DTLVERTEX, size_t)
#define std3D_SetRenderState_TYPE void (J3DAPI*)(Std3DRenderState)
#define std3D_AllocSystemTexture_TYPE void (J3DAPI*)(tSystemTexture*, tVBuffer**, size_t, StdColorFormatType)
#define std3D_GetValidDimensions_TYPE void (J3DAPI*)(uint32_t, uint32_t, uint32_t*, uint32_t*)
#define std3D_ClearSystemTexture_TYPE void (J3DAPI*)(tSystemTexture*)
#define std3D_AddToTextureCache_TYPE void (J3DAPI*)(tSystemTexture*, StdColorFormatType)
#define std3D_GetMipMapCount_TYPE size_t (J3DAPI*)(const tSystemTexture*)
#define std3D_ResetTextureCache_TYPE void (*)(void)
#define std3D_UpdateFrameCount_TYPE void (J3DAPI*)(tSystemTexture*)
#define std3D_FindClosestFormat_TYPE size_t (J3DAPI*)(const ColorInfo*)
#define std3D_InitRenderState_TYPE int (*)(void)
#define std3D_SetMipmapFilter_TYPE int (J3DAPI*)(Std3DMipmapFilterType)
#define std3D_SetProjection_TYPE int (J3DAPI*)(float, float, float)
#define std3D_EnableFog_TYPE void (J3DAPI*)(int, float)
#define std3D_SetFog_TYPE void (J3DAPI*)(float, float, float, float, float)
#define std3D_ClearZBuffer_TYPE void (*)(void)
#define std3D_CreateViewport_TYPE int (*)(void)
#define std3D_GetZBufferFormat_TYPE void (J3DAPI*)(DDPIXELFORMAT*)
#define std3D_EnumZBufferFormatsCallback_TYPE HRESULT (CALLBACK*)(LPDDPIXELFORMAT, DDPIXELFORMAT*)
#define std3D_D3DEnumDevicesCallback_TYPE HRESULT (CALLBACK*)(GUID*, LPSTR, LPSTR, LPD3DDEVICEDESC, LPD3DDEVICEDESC, LPVOID)
#define std3D_EnumTextureFormatsCallback_TYPE HRESULT (CALLBACK*)(LPDDPIXELFORMAT, LPVOID)
#define std3D_AddTextureToCacheList_TYPE void (J3DAPI*)(tSystemTexture*)
#define std3D_RemoveTextureFromCacheList_TYPE void (J3DAPI*)(tSystemTexture*)
#define std3D_PurgeTextureCache_TYPE int (J3DAPI*)(size_t)
#define std3D_D3DGetStatus_TYPE const char* (J3DAPI*)(HRESULT)
#define std3D_BuildDisplayEnvironment_TYPE StdDisplayEnvironment* (J3DAPI*)()
#define std3D_FreeDisplayEnvironment_TYPE void (J3DAPI*)(StdDisplayEnvironment*)
#define std3D_SetFindAllDevices_TYPE void (J3DAPI*)(int)
#define stdHashtbl_New_TYPE tHashTable* (J3DAPI*)(size_t)
#define CalculateHash_TYPE unsigned int (J3DAPI*)(const char*, signed int)
#define GetNextPrime_TYPE int (J3DAPI*)(signed int)
#define isPrime_TYPE int (J3DAPI*)(size_t)
#define stdHashtbl_nextPrime_TYPE size_t (J3DAPI*)(size_t)
#define stdHashtbl_Free_TYPE void (J3DAPI*)(tHashTable*)
#define stdHashtbl_FreeListNodes_TYPE void (J3DAPI*)(tLinkListNode*)
#define stdHashtbl_Add_TYPE int (J3DAPI*)(tHashTable*, const char*, void*)
#define stdHashtbl_GetTailNode_TYPE tLinkListNode* (J3DAPI*)(const tLinkListNode*)
#define stdHashtbl_Find_TYPE void* (J3DAPI*)(const tHashTable*, const char*)
#define stdHashtbl_FindNode_TYPE tLinkListNode* (J3DAPI*)(const tHashTable*, const char*, int*)
#define stdHashtbl_Remove_TYPE int (J3DAPI*)(tHashTable*, const char*)
#define stdComm_Send_TYPE int32_t (J3DAPI*)(DPID, DPID, const void*, uint32_t, uint32_t)
#define stdComm_Receive_TYPE int32_t (J3DAPI*)(DPID*, void*, size_t*)
#define stdComm_CloseGame_TYPE void (*)(void)
#define stdComm_RejoinSession_TYPE int (J3DAPI*)(DPID*, const wchar_t*)
#define stdComm_GetSessionSettings_TYPE int (J3DAPI*)(StdCommGame*)
#define stdComm_IsGameActive_TYPE int (J3DAPI*)(void)
#define stdComm_IsGameHost_TYPE int (J3DAPI*)(void)
#define stdComm_UpdatePlayers_TYPE int (J3DAPI*)(size_t)
#define stdComm_CreatePlayer_TYPE DPID (J3DAPI*)(const wchar_t*)
#define stdComm_DestroyPlayer_TYPE void (J3DAPI*)(DPID)
#define stdComm_GetNumPlayers_TYPE size_t (*)(void)
#define stdComm_VerifyPlayer_TYPE int (J3DAPI*)(DPID)
#define stdComm_GetPlayerID_TYPE DPID (J3DAPI*)(size_t)
#define stdComm_EnumPlayersCallback_TYPE BOOL (__stdcall*)(DPID, DOWRD, LPCDPNAME, DOWRD, LPVOID)
#define stdComm_ProcessSystemMessage_TYPE int (J3DAPI*)(LPDPMSG_GENERIC, DPID*)
#define stdComm_SessionToSettings_TYPE void (J3DAPI*)(LPDPSESSIONDESC2, StdCommGame*)
#define stdComm_DPGetStatus_TYPE const char* (J3DAPI*)(HRESULT)
#define stdMath_FlexPower_TYPE float (J3DAPI*)(float, int)
#define stdMath_NormalizeAngle_TYPE float (J3DAPI*)(float)
#define stdMath_NormalizeAngleAcute_TYPE float (J3DAPI*)(float)
#define stdMath_SinCos_TYPE void (J3DAPI*)(float, float*, float*)
#define stdMath_Tan_TYPE float (J3DAPI*)(float)
#define stdMath_ArcSin1_TYPE float (J3DAPI*)(float)
#define stdMath_ArcSin3_TYPE float (J3DAPI*)(float)
#define stdMath_ArcTan4_TYPE float (J3DAPI*)(float, float)
#define stdMath_Dist2D1_TYPE float (J3DAPI*)(float, float)
#define stdMath_Dist3D1_TYPE float (J3DAPI*)(float, float, float)
#define stdStartup_TYPE void (J3DAPI*)(tHostServices*)
#define stdShutdown_TYPE void (*)(void)
#define stdPrintf_TYPE void (J3DAPI*)(tPrintfFunc fpPrint, const char* pFilePath, unsigned int linenum, const char* format, ...)
#define stdConsolePrintf_TYPE int (*)(const char*, ...)
#define stdFileFromPath_TYPE const char* (J3DAPI*)(const char*)
#define stdCalcBitPos_TYPE int (J3DAPI*)(int)
#define stdFileOpen_TYPE tFileHandle (J3DAPI*)(const char*, const char*)
#define stdFileClose_TYPE int (J3DAPI*)(tFileHandle)
#define stdFileRead_TYPE size_t (J3DAPI*)(tFileHandle, void*, size_t)
#define stdFileWrite_TYPE size_t (J3DAPI*)(tFileHandle, const void*, size_t)
#define stdFileGets_TYPE char* (J3DAPI*)(tFileHandle, char*, size_t)
#define stdFileGetws_TYPE wchar_t* (J3DAPI*)(tFileHandle, wchar_t*, size_t)
#define stdFileEof_TYPE int (J3DAPI*)(tFileHandle)
#define stdFileTell_TYPE int (J3DAPI*)(tFileHandle)
#define stdFileSize_TYPE size_t (J3DAPI*)(const char*)
#define stdFilePrintf_TYPE int (*)(tFileHandle, const char*, ...)
#define stdFileSeek_TYPE int (J3DAPI*)(tFileHandle, int, int)
#define stdMemory_Startup_TYPE int (*)(void)
#define stdMemory_Shutdown_TYPE void (*)(void)
#define stdMemory_Open_TYPE int (*)(void)
#define stdMemory_Close_TYPE void (*)(void)
#define stdMemory_Malloc_TYPE void* (J3DAPI*)(size_t, const char*, size_t)
#define stdMemory_Free_TYPE void (J3DAPI*)(void*)
#define stdMemory_Realloc_TYPE void* (J3DAPI*)(void*, size_t, const char*, size_t)
#define stdMemory_BlockMalloc_TYPE void* (J3DAPI*)(size_t)
#define stdMemory_BlockFree_TYPE void (J3DAPI*)(void*)
#define stdMemory_BlockRealloc_TYPE void* (J3DAPI*)(void*, size_t)
#define stdMemory_BlockAlloc_TYPE void* (J3DAPI*)(size_t)
#define stdWin95_SetWindow_TYPE void (J3DAPI*)(HWND)
#define stdWin95_GetWindow_TYPE HWND (J3DAPI*)()
#define stdWin95_SetInstance_TYPE void (J3DAPI*)(HINSTANCE)
#define stdWin95_GetInstance_TYPE HINSTANCE (*)(void)
#define stdWin95_SetGuid_TYPE void (J3DAPI*)(const GUID*)
#define stdConffile_Open_TYPE int (J3DAPI*)(const char*)
#define stdConffile_OpenWrite_TYPE int (J3DAPI*)(const char*)
#define stdConffile_OpenMode_TYPE int (J3DAPI*)(const char*, const char*)
#define stdConffile_Close_TYPE void (*)(void)
#define stdConffile_CloseWrite_TYPE void (*)(void)
#define stdConffile_Write_TYPE int (J3DAPI*)(const void*, size_t)
#define stdConffile_Read_TYPE int (J3DAPI*)(void*, size_t)
#define stdConffile_ReadArgsFromStr_TYPE int (J3DAPI*)(char*)
#define stdConffile_ReadArgs_TYPE int (*)(void)
#define stdConffile_ReadLine_TYPE int (*)(void)
#define stdConffile_GetFileHandle_TYPE tFileHandle (*)(void)
#define stdConffile_GetLineNumber_TYPE size_t (*)(void)
#define stdConffile_GetFilename_TYPE const char* (*)(void)
#define stdConffile_PushStack_TYPE void (*)(void)
#define stdConffile_PopStack_TYPE void (*)(void)
#define stdPlatform_InitServices_TYPE int (J3DAPI*)(tHostServices*)
#define stdPlatform_ClearServices_TYPE void (J3DAPI*)(tHostServices*)
#define stdPlatform_GetTimeMsec_TYPE unsigned int(*)(void)
#define stdPlatform_Assert_TYPE void (J3DAPI*)(const char*, const char*, int)
#define stdPlatform_Printf_TYPE int (*)(const char*, ...)
#define stdPlatform_AllocHandle_TYPE void* (J3DAPI*)(size_t)
#define stdPlatform_FreeHandle_TYPE void (J3DAPI*)(void*)
#define stdPlatform_ReallocHandle_TYPE void* (J3DAPI*)(void*, size_t)
#define stdPlatform_LockHandle_TYPE int (J3DAPI*)(int)
#define stdPlatform_UnlockHandle_TYPE void (J3DAPI*)()
#define stdGob_Startup_TYPE void (J3DAPI*)(tHostServices*)
#define stdGob_Shutdown_TYPE void (J3DAPI*)()
#define stdGob_Load_TYPE Gob* (J3DAPI*)(const char*, int, int)
#define stdGob_LoadEntry_TYPE int (J3DAPI*)(Gob*, const char*, int, int)
#define stdGob_Free_TYPE void (J3DAPI*)(Gob*)
#define stdGob_FreeEntry_TYPE void (J3DAPI*)(Gob*)
#define stdGob_FileOpen_TYPE GobFileHandle* (J3DAPI*)(Gob*, const char*)
#define stdGob_FileClose_TYPE void (J3DAPI*)(GobFileHandle*)
#define stdGob_FileSeek_TYPE int (J3DAPI*)(GobFileHandle*, int, int)
#define stdGob_FileTell_TYPE int (J3DAPI*)(GobFileHandle*)
#define stdGob_FileEOF_TYPE int (J3DAPI*)(GobFileHandle*)
#define stdGob_FileRead_TYPE size_t (J3DAPI*)(GobFileHandle*, void*, const size_t)
#define stdGob_FileGets_TYPE const char* (J3DAPI*)(GobFileHandle*, char*, size_t)
#define stdEffect_Startup_TYPE void (*)(void)
#define stdEffect_Reset_TYPE void (*)(void)
#define stdEffect_SetFadeFactor_TYPE void (J3DAPI*)(int, float)
#define stdEffect_GetFadeFactor_TYPE const tStdFadeFactor* (J3DAPI*)()
#define stdConsole_Startup_TYPE int (J3DAPI*)(const char*, int, int)
#define stdConsole_Shutdown_TYPE void (*)(void)
#define stdConsole_SetAttributes_TYPE int (J3DAPI*)(WORD)
#define stdConsole_SetConsoleTextAttribute_TYPE int (J3DAPI*)(WORD)
#define stdConsole_InitOutputConsole_TYPE int (*)(void)
#define stdConsole_WriteConsole_TYPE int (J3DAPI*)(const char*, uint32_t)
#define stdStrTable_Load_TYPE int (J3DAPI*)(tStringTable*, const char*)
#define stdStrTable_ParseLiteral_TYPE char* (J3DAPI*)(const char*, char**, char**)
#define stdStrTable_Free_TYPE void (J3DAPI*)(tStringTable*)
#define stdStrTable_GetValue_TYPE wchar_t* (J3DAPI*)(const tStringTable*, const char*)
#define stdStrTable_GetValueOrKey_TYPE wchar_t* (J3DAPI*)(const tStringTable*, const char*)
#define stdStrTable_ReadLine_TYPE int (J3DAPI*)(tFileHandle, char*, int)
#define stdBmp_WriteVBuffer_TYPE int (J3DAPI*)(const char*, tVBuffer*)
#define stdBmp_Load_TYPE HBITMAP (J3DAPI*)(const char*)
#define stdFnames_FindMedName_TYPE const char* (J3DAPI*)(const char*)
#define stdFnames_FindExt_TYPE char* (J3DAPI*)(const char*)
#define stdFnames_StripExtAndDot_TYPE void (J3DAPI*)(char*)
#define stdFnames_ChangeExt_TYPE void (J3DAPI*)(char*, const char*)
#define stdFnames_Concat_TYPE void (J3DAPI*)(char*, const char*, size_t)
#define stdFnames_MakePath_TYPE void (J3DAPI*)(char*, int, const char*, const char*)
#define stdUtil_Format_TYPE int (*)(char*, size_t, const char*, ...)
#define stdUtil_StringSplit_TYPE char* (J3DAPI*)(const char*, char*, unsigned int, char*)
#define stdUtil_ParseLiteral_TYPE char* (J3DAPI*)(const char*, char*, unsigned int)
#define stdUtil_ToWStringEx_TYPE int (J3DAPI*)(wchar_t*, const char*, unsigned int)
#define stdUtil_ToAStringEx_TYPE void (J3DAPI*)(char*, const wchar_t*, unsigned int)
#define stdUtil_ToWString_TYPE wchar_t* (J3DAPI*)(const char*)
#define stdUtil_ToAString_TYPE char* (J3DAPI*)(const wchar_t*)
#define stdUtil_ToLower_TYPE void (J3DAPI*)(char*)
#define stdUtil_StrCmp_TYPE int (J3DAPI*)(const char*, const char*)
#define stdFileUtil_NewFind_TYPE FindFileData* (J3DAPI*)(const char*, int, const char*)
#define stdFileUtil_DisposeFind_TYPE void (J3DAPI*)(FindFileData*)
#define stdFileUtil_FindNext_TYPE int (J3DAPI*)(FindFileData*, tFoundFileInfo*)
#define stdFileUtil_MkDir_TYPE int (J3DAPI*)(const char*)
#define stdFileUtil_FileExists_TYPE int (J3DAPI*)(const char*)
#define stdCircBuf_New_TYPE int (J3DAPI*)(tCircularBuffer*, int, int)
#define stdCircBuf_Free_TYPE void (J3DAPI*)(tCircularBuffer*)
#define stdCircBuf_Purge_TYPE void (J3DAPI*)(tCircularBuffer*)
#define stdCircBuf_GetNextElement_TYPE void* (J3DAPI*)(tCircularBuffer*)
#define stdColor_ColorConvertOneRow_TYPE void (J3DAPI*)(uint8_t*, const ColorInfo*, const uint8_t*, const ColorInfo*, int, int, LPDDCOLORKEY)
#define stdLinkList_AddNode_TYPE void (J3DAPI*)(tLinkListNode*, tLinkListNode*)
#define stdLinkList_RemoveNode_TYPE void (J3DAPI*)(tLinkListNode*)

#endif // STD_RTI_SYMBOLS_H
