#ifndef SOUND_RTI_SYMBOLS_H
#define SOUND_RTI_SYMBOLS_H
#include <j3dcore/j3d.h>
#include <sound/types.h>

#define SoundDriver_Open_TYPE int (J3DAPI*)(int, int, HWND, LPDIRECTSOUND, SoundCalcListenerSoundMixFunc, SoundDriverGetSoundBufferDataFunc, tPrintfFunc)
#define SoundDriver_Close_TYPE void (*)(void)
#define SoundDriver_SetMaxVolume_TYPE void (J3DAPI*)(float)
#define SoundDriver_CreateAndPlay_TYPE LPDIRECTSOUNDBUFFER (J3DAPI*)(size_t, size_t, size_t, const uint8_t*, size_t, tSoundChannelFlag*, const LPDIRECTSOUNDBUFFER)
#define SoundDriver_Release_TYPE void (J3DAPI*)(LPDIRECTSOUNDBUFFER)
#define SoundDriver_Play_TYPE void (J3DAPI*)(LPDIRECTSOUNDBUFFER, int)
#define SoundDriver_Stop_TYPE void (J3DAPI*)(LPDIRECTSOUNDBUFFER)
#define SoundDriver_SetVolume_TYPE void (J3DAPI*)(LPDIRECTSOUNDBUFFER, float)
#define SoundDriver_GetVolume_TYPE float (J3DAPI*)(LPDIRECTSOUNDBUFFER)
#define SoundDriver_SetPan_TYPE void (J3DAPI*)(LPDIRECTSOUNDBUFFER, float)
#define SoundDriver_SetFrequency_TYPE void (J3DAPI*)(LPDIRECTSOUNDBUFFER, float)
#define SoundDriver_GetFrequency_TYPE float (J3DAPI*)(LPDIRECTSOUNDBUFFER)
#define SoundDriver_GetCurrentPosition_TYPE size_t (J3DAPI*)(LPDIRECTSOUNDBUFFER)
#define SoundDriver_GetStatusAndCaps_TYPE tSoundChannelFlag (J3DAPI*)(LPDIRECTSOUNDBUFFER)
#define SoundDriver_SetListenerPosition_TYPE void (J3DAPI*)(const rdVector3*, const rdVector3*, const rdVector3*, const rdVector3*)
#define SoundDriver_ListenerCommitDeferred_TYPE void (*)(void)
#define SoundDriver_SetPosAndVelocity_TYPE void (J3DAPI*)(LPDIRECTSOUNDBUFFER, float, float, float, float, float, float, float, float)
#define SoundDriver_Update3DSound_TYPE int (J3DAPI*)(LPDIRECTSOUNDBUFFER*, float, float, float, float, float, tSoundChannelFlag*, float, float, SoundEnvFlags)
#define SoundDriver_SetGlobals_TYPE void (J3DAPI*)(float, float, float, float, float)
#define SoundDriver_Use3DCaps_TYPE int (*)(void)
#define SoundDriver_GetDSound_TYPE LPDIRECTSOUND (*)(void)
#define SoundDriver_CreateDirectSound_TYPE LPDIRECTSOUND (J3DAPI*)(int)
#define SoundDriver_ReleaseDirectSound_TYPE void (J3DAPI*)(LPDIRECTSOUND)
#define SoundDriver_CreateListener_TYPE void (*)(void)
#define SoundDriver_ReleaseListener_TYPE void (*)(void)
#define SoundDriver_SetOuputFormat_TYPE void (J3DAPI*)(LPDIRECTSOUND, uint32_t, uint32_t, uint32_t)
#define SoundDriver_GetPrimaryDSBuffer_TYPE LPDIRECTSOUNDBUFFER (J3DAPI*)(LPDIRECTSOUND)
#define SoundDriver_ReleasePrimaryDSBuffer_TYPE void (*)(void)
#define SoundDriver_GetDecibelVolume_TYPE int (J3DAPI*)(float)
#define SoundDriver_GetIntPan_TYPE int (J3DAPI*)(float)
#define SoundDriver_GetVolumeFromDecibels_TYPE float (J3DAPI*)(int)
#define SoundDriver_InitPanTable_TYPE void (*)(void)
#define SoundDriver_DSCheckStatus_TYPE HRESULT (J3DAPI*)(HRESULT, size_t)
#define SoundDriver_CalcListeneSoundMix_TYPE void (J3DAPI*)(float, float, float, float, float, float*, float*, float*, float, float, SoundEnvFlags)
#define SoundDriver_CalcDistToListener_TYPE double (J3DAPI*)(float, float, float, float, float, float)
#define SoundDriver_RestoreSoundBufferData_TYPE void (J3DAPI*)(LPDIRECTSOUNDBUFFER)
#define SoundDriver_Sleep_TYPE void (J3DAPI*)(unsigned int)
#define AudioLib_ParseWaveFileHeader_TYPE const uint8_t* (J3DAPI*)(const uint8_t*, int*, uint32_t*, uint32_t*, uint32_t*, uint32_t*, uint32_t*, uint32_t*, uint32_t*)
#define AudioLib_Compress_TYPE int (J3DAPI*)(tAudioCompressorState*, uint8_t*, const uint8_t*, int, unsigned int)
#define AudioLib_ResetCompressor_TYPE void (J3DAPI*)(tAudioCompressorState*)
#define AudioLib_Uncompress_TYPE void (J3DAPI*)(tAudioCompressorState*, uint8_t*, const uint8_t*, unsigned int)
#define AudioLib_GetMouthPosition_TYPE int (J3DAPI*)(uint8_t*, int, uint8_t*, uint8_t*)
#define AudioLib_GenerateLipSynchBlock_TYPE int (J3DAPI*)(uint8_t*, const uint8_t*, unsigned int, char, char, int, int, int, int, int)
#define AudioLib_CompressBlock_TYPE int (J3DAPI*)(tAudioCompressorState*, uint8_t*, int16_t*, int, unsigned int, int, int)
#define AudioLib_UncompressBlock_TYPE void (J3DAPI*)(tAudioCompressorState*, uint8_t*, const uint8_t*, int, unsigned int, int)
#define AudioLib_WVSMCompressBlock_TYPE int (J3DAPI*)(uint8_t*, const uint8_t*, int, FILE*)
#define AudioLib_WVSMUncompressBlock_TYPE int (J3DAPI*)(uint8_t*, const uint8_t*, int)
#define Sound_Initialize_TYPE int (J3DAPI*)(tHostServices*)
#define Sound_Uninitialize_TYPE void (*)(void)
#define Sound_Startup_TYPE int (*)(void)
#define Sound_Shutdown_TYPE void (*)(void)
#define Sound_Open_TYPE int (J3DAPI*)(SoundOpenFlags, size_t, SoundGetThingInfoCallback, SoundCalcListenerSoundMixFunc, HWND)
#define Sound_Close_TYPE void (*)(void)
#define Sound_Save_TYPE int (J3DAPI*)(tFileHandle)
#define Sound_Restore_TYPE int (J3DAPI*)(tFileHandle)
#define Sound_Pause_TYPE void (*)(void)
#define Sound_Resume_TYPE void (*)(void)
#define Sound_Set3DGlobals_TYPE void (J3DAPI*)(float, float, float, float, float)
#define Sound_Has3DHW_TYPE int (*)(void)
#define Sound_Set3DHWState_TYPE void (J3DAPI*)(int)
#define Sound_Get3DHWState_TYPE int (*)(void)
#define Sound_GetMemoryUsage_TYPE unsigned int (J3DAPI*)()
#define Sound_Load_TYPE tSoundHandle (J3DAPI*)(const char*, uint32_t*)
#define Sound_LoadStatic_TYPE tSoundHandle (J3DAPI*)(const char*, uint32_t*)
#define Sound_Reset_TYPE void (J3DAPI*)(int)
#define Sound_EnableLoad_TYPE int (J3DAPI*)(int)
#define Sound_ExportStaticBank_TYPE size_t (J3DAPI*)(tFileHandle)
#define Sound_ImportStaticBank_TYPE int (J3DAPI*)(tFileHandle)
#define Sound_ExportNormalBank_TYPE size_t (J3DAPI*)(tFileHandle)
#define Sound_ImportNormalBank_TYPE int (J3DAPI*)(tFileHandle)
#define Sound_SkipSoundFileSection_TYPE int (J3DAPI*)(tFileHandle)
#define Sound_GetSoundHandle_TYPE tSoundHandle (J3DAPI*)(uint32_t)
#define Sound_GetSoundIndex_TYPE siuze_t (J3DAPI*)(tSoundHandle)
#define Sound_GetChannelHandle_TYPE tSoundChannelHandle (J3DAPI*)(int)
#define Sound_GetChannelGUID_TYPE int (J3DAPI*)(tSoundChannelHandle)
#define Sound_GetSoundFilename_TYPE const char* (J3DAPI*)(unsigned int)
#define Sound_GetLengthMsec_TYPE size_t (J3DAPI*)(unsigned int)
#define Sound_SetMaxVolume_TYPE void (J3DAPI*)(float)
#define Sound_GetMaxVolume_TYPE float (*)(void)
#define Sound_Play_TYPE tSoundChannelHandle (J3DAPI*)(tSoundHandle, float, float, int, tSoundChannelFlag, int)
#define Sound_PlayPos_TYPE tSoundChannelHandle (J3DAPI*)(tSoundHandle, float, int, tSoundChannelFlag, float, float, float, int, float, float, SoundEnvFlags)
#define Sound_PlayThing_TYPE tSoundChannelHandle (J3DAPI*)(tSoundHandle, float, int, tSoundChannelFlag, int, int, float, float)
#define Sound_StopChannel_TYPE void (J3DAPI*)(tSoundChannelHandle)
#define Sound_StopAllSounds_TYPE void (*)(void)
#define Sound_StopThing_TYPE void (J3DAPI*)(int, unsigned int)
#define Sound_SetVolume_TYPE void (J3DAPI*)(tSoundChannelHandle, float)
#define Sound_FadeVolume_TYPE void (J3DAPI*)(tSoundChannelHandle, float, float)
#define Sound_SetVolumeThing_TYPE void (J3DAPI*)(int, unsigned int, float)
#define Sound_FadeVolumeThing_TYPE void (J3DAPI*)(int, unsigned int, float, float)
#define Sound_IsThingFadingVol_TYPE int (J3DAPI*)(int, unsigned int)
#define Sound_SetPitch_TYPE void (J3DAPI*)(tSoundChannelHandle, float)
#define Sound_GetPitch_TYPE float (J3DAPI*)(tSoundChannelHandle)
#define Sound_FadePitch_TYPE void (J3DAPI*)(tSoundChannelHandle, float, float)
#define Sound_SetPitchThing_TYPE void (J3DAPI*)(int, unsigned int, float)
#define Sound_GetChannelFlags_TYPE tSoundChannelFlag (J3DAPI*)(tSoundChannelHandle)
#define Sound_Update_TYPE void (J3DAPI*)(const rdVector3*, const rdVector3*, const rdVector3*, const rdVector3*)
#define Sound_GenerateLipSync_TYPE int (J3DAPI*)(tSoundChannelHandle, uint8_t*, uint8_t*, int)
#define Sound_SetReverseSound_TYPE void (J3DAPI*)(int)
#define Sound_GetNextHandle_TYPE tSoundHandle (*)(void)
#define Sound_GetNextChannelHandle_TYPE tSoundChannelHandle (*)(void)
#define Sound_GetFreeCache_TYPE size_t (J3DAPI*)(size_t, size_t)
#define Sound_IncreaseFreeCache_TYPE void (J3DAPI*)(size_t, size_t)
#define Sound_WriteSoundFilepathToBank_TYPE size_t (J3DAPI*)(size_t, const char*, size_t)
#define Sound_GetDeltaTime_TYPE size_t (*)(void)
#define Sound_GetSoundInfo_TYPE SoundInfo* (J3DAPI*)(tSoundHandle)
#define Sound_GetChannel_TYPE tSoundChannel* (J3DAPI*)(tSoundChannelHandle)
#define Sound_GetChannelBySoundHandle_TYPE tSoundChannel* (J3DAPI*)(tSoundHandle)
#define Sound_GetSoundBufferData_TYPE uint8_t* (J3DAPI*)(LPDIRECTSOUNDBUFFER, size_t*, uint32_t*)
#define Sound_MemFileRead_TYPE size_t (J3DAPI*)(tFileHandle, void*, size_t)
#define Sound_MemFileWrite_TYPE size_t (J3DAPI*)(tFileHandle, const void*, size_t)
#define Sound_MemFileReset_TYPE tFileHandle (*)(void)
#define Sound_MemFileFree_TYPE void (*)(void)
#define Sound_StopAllNonStaticSounds_TYPE void (*)(void)
#define Sound_ExportBank_TYPE int (J3DAPI*)(tFileHandle, size_t)
#define Sound_ImportBank_TYPE int (J3DAPI*)(tFileHandle, size_t)
#define Sound_ReadFile_TYPE int (J3DAPI*)(tFileHandle, void*, size_t)

#endif // SOUND_RTI_SYMBOLS_H
